import type { CompatibilityAnswers, UserProfile } from "./types";

const answers = (
  intellectualChallenge: number,
  communicationFrequency: number,
  growthMindset: number,
  qualityTime: number,
  appreciation: number,
  drinkingComfort: number,
  weedComfort: number,
  activeLifestyle: number,
  financialSecurity: number,
  morningPerson: number,
  ambitionBalance: number,
  childrenPreference: number
): CompatibilityAnswers => ({
  intellectualChallenge,
  communicationFrequency,
  growthMindset,
  qualityTime,
  appreciation,
  drinkingComfort,
  weedComfort,
  activeLifestyle,
  financialSecurity,
  morningPerson,
  ambitionBalance,
  childrenPreference
});

export const demoUsers: UserProfile[] = [
  {
    id: "mia",
    email: "mia@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Mia",
    age: 21,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Law student, coffee loyalist, and weekend market regular.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 6, 4, 2, 5, 6, 5, 3, 5)
  },
  {
    id: "noah",
    email: "noah@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Noah",
    age: 22,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Computer science student who likes climbing, film nights, and dumplings.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 4, 6, 5, 5, 4, 2, 6, 5, 4, 4, 5)
  },
  {
    id: "ava",
    email: "ava@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ava",
    age: 20,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Music, art history, and finding Canberra's best pastries.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 5, 6, 6, 5, 4, 3, 4, 2, 2, 3)
  },
  {
    id: "sam",
    email: "sam@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Sam",
    age: 23,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Philosophy tutor, trivia menace, and board game enthusiast.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 4, 5, 4, 5, 5, 5, 3, 5, 3, 3, 4)
  },
  {
    id: "leo",
    email: "leo@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Leo",
    age: 24,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Engineering student, sunrise runner, and loyal to late-night ramen.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 5, 3, 2, 7, 5, 6, 4, 4)
  },
  {
    id: "ivy",
    email: "ivy@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ivy",
    age: 22,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Psychology student who loves bookstores, hikes, and elaborate playlists.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 6, 6, 7, 4, 2, 4, 5, 3, 3, 5)
  },
  {
    id: "ethan",
    email: "ethan@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ethan",
    age: 21,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Economics major, basketball regular, and always up for gelato.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 4, 5, 4, 5, 3, 1, 6, 6, 5, 5, 4)
  },
  {
    id: "zara",
    email: "zara@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Zara",
    age: 23,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "International relations student, gallery wanderer, and picnic planner.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 6, 5, 6, 6, 5, 3, 3, 4, 2, 3, 3)
  },
  {
    id: "kai",
    email: "kai@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Kai",
    age: 20,
    gender: "non_binary",
    interestedIn: ["man", "woman", "non_binary"],
    bio: "Design student, zine maker, and champion of cosy movie nights.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 5, 5, 6, 6, 4, 4, 3, 3, 2, 2, 4)
  },
  {
    id: "lucas",
    email: "lucas@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Lucas",
    age: 25,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Medical science student, meal-prep devotee, and trivia night organiser.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 6, 4, 5, 2, 1, 6, 7, 5, 6, 6)
  },
  {
    id: "nina",
    email: "nina@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Nina",
    age: 21,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Maths student who likes salsa classes, long walks, and bad puns.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 5, 6, 5, 6, 4, 2, 5, 5, 4, 4, 5)
  },
  {
    id: "oscar",
    email: "oscar@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Oscar",
    age: 22,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Politics student, live music fan, and collector of vintage jackets.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 4, 5, 5, 6, 5, 4, 3, 2, 3, 2)
  },
  {
    id: "priya",
    email: "priya@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Priya",
    age: 24,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Public policy student, amateur baker, and weekend lake walker.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 4, 7, 5, 7, 3, 1, 4, 6, 5, 4, 6)
  },
  {
    id: "rafa",
    email: "rafa@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Rafa",
    age: 23,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Architecture student, cyclist, and always scouting the best coffee.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 5, 5, 4, 6, 5, 3, 7, 4, 6, 5, 4)
  },
  {
    id: "talia",
    email: "talia@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Talia",
    age: 20,
    gender: "woman",
    interestedIn: ["woman"],
    bio: "Biology student, plant parent, and quiet brunch enthusiast.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 3, 5, 4, 6, 2, 1, 3, 5, 5, 2, 5)
  },
  {
    id: "max",
    email: "max@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Max",
    age: 26,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Law student, swimmer, and strong believer in Sunday reset walks.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 3, 6, 3, 5, 3, 2, 6, 7, 6, 5, 5)
  },
  {
    id: "remy",
    email: "remy@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Remy",
    age: 22,
    gender: "non_binary",
    interestedIn: ["woman", "non_binary"],
    bio: "Creative writing student, cafe reader, and board game strategist.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 5, 4, 6, 5, 4, 4, 2, 3, 1, 2, 3)
  },
  {
    id: "grace",
    email: "grace@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Grace",
    age: 25,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "PhD candidate, sourdough experimenter, and sunset chaser.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 7, 4, 6, 3, 1, 5, 7, 4, 6, 6)
  },
  {
    id: "henry",
    email: "henry@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Henry",
    age: 21,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Statistics student, tennis player, and fan of low-key dinner dates.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 4, 5, 5, 5, 3, 2, 6, 6, 5, 4, 5)
  },
  {
    id: "lena",
    email: "lena@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Lena",
    age: 22,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Computer science student, pottery beginner, and dessert sharer.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 6, 4, 3, 4, 5, 3, 4, 4)
  },
  {
    id: "ben",
    email: "ben@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ben",
    age: 24,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Environmental studies student, climber, and farmers market regular.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 5, 5, 5, 5, 5, 4, 7, 3, 6, 3, 3)
  },
  {
    id: "sienna",
    email: "sienna@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Sienna",
    age: 23,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Commerce student, netball teammate, and brunch reservation expert.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 6, 4, 6, 5, 6, 5, 6, 3, 4, 4, 2)
  },
  {
    id: "eli",
    email: "eli@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Eli",
    age: 20,
    gender: "non_binary",
    interestedIn: ["man", "woman"],
    bio: "History student, op-shop hunter, and fan of spontaneous day trips.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 5, 5, 6, 4, 3, 4, 4, 2, 3, 4)
  },
  {
    id: "maya",
    email: "maya@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Maya",
    age: 24,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Anthropology student, ceramicist, and lover of slow Sundays.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 3, 6, 4, 7, 2, 1, 3, 5, 4, 2, 5)
  },
  {
    id: "tom",
    email: "tom@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Tom",
    age: 25,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Physics student, jazz listener, and excellent pancake maker.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 3, 6, 3, 5, 2, 1, 4, 7, 3, 6, 5)
  },
  {
    id: "ayla",
    email: "ayla@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ayla",
    age: 21,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Music student, choir regular, and always planning the next picnic.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 6, 5, 7, 6, 5, 3, 3, 4, 2, 2, 4)
  },
  {
    id: "jules",
    email: "jules@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Jules",
    age: 23,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Linguistics student, baker, and lover of long conversations.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 6, 3, 2, 3, 5, 3, 3, 5)
  },
  {
    id: "daniel",
    email: "daniel@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Daniel",
    age: 22,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Data science student, casual guitarist, and fan of night markets.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 5, 6, 5, 5, 4, 5, 4, 2, 3, 3)
  }
];
