import type { CompatibilityAnswers, UserProfile } from "./types";

const answers = (
  intellectualChallenge: number,
  communicationFrequency: number,
  growthMindset: number,
  qualityTime: number,
  appreciation: number,
  drinkingComfort: number,
  weedComfort: number,
  activeLifestyle: number,
  financialSecurity: number,
  morningPerson: number,
  ambitionBalance: number,
  childrenPreference: number
): CompatibilityAnswers => ({
  intellectualChallenge,
  communicationFrequency,
  growthMindset,
  qualityTime,
  appreciation,
  drinkingComfort,
  weedComfort,
  activeLifestyle,
  financialSecurity,
  morningPerson,
  ambitionBalance,
  childrenPreference
});

export const demoUsers: UserProfile[] = [
  {
    id: "mia",
    email: "mia@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Mia",
    age: 21,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Law student, coffee loyalist, and weekend market regular.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 6, 4, 2, 5, 6, 5, 3, 5)
  },
  {
    id: "noah",
    email: "noah@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Noah",
    age: 22,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Computer science student who likes climbing, film nights, and dumplings.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 4, 6, 5, 5, 4, 2, 6, 5, 4, 4, 5)
  },
  {
    id: "ava",
    email: "ava@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ava",
    age: 20,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Music, art history, and finding Canberra's best pastries.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 5, 6, 6, 5, 4, 3, 4, 2, 2, 3)
  },
  {
    id: "sam",
    email: "sam@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Sam",
    age: 23,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Philosophy tutor, trivia menace, and board game enthusiast.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 4, 5, 4, 5, 5, 5, 3, 5, 3, 3, 4)
  },
  {
    id: "leo",
    email: "leo@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Leo",
    age: 24,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Engineering student, sunrise runner, and loyal to late-night ramen.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 5, 3, 2, 7, 5, 6, 4, 4)
  },
  {
    id: "ivy",
    email: "ivy@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ivy",
    age: 22,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Psychology student who loves bookstores, hikes, and elaborate playlists.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 6, 6, 7, 4, 2, 4, 5, 3, 3, 5)
  },
  {
    id: "ethan",
    email: "ethan@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ethan",
    age: 21,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Economics major, basketball regular, and always up for gelato.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 4, 5, 4, 5, 3, 1, 6, 6, 5, 5, 4)
  },
  {
    id: "zara",
    email: "zara@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Zara",
    age: 23,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "International relations student, gallery wanderer, and picnic planner.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 6, 5, 6, 6, 5, 3, 3, 4, 2, 3, 3)
  },
  {
    id: "kai",
    email: "kai@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Kai",
    age: 20,
    gender: "non_binary",
    interestedIn: ["man", "woman", "non_binary"],
    bio: "Design student, zine maker, and champion of cosy movie nights.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 5, 5, 6, 6, 4, 4, 3, 3, 2, 2, 4)
  },
  {
    id: "lucas",
    email: "lucas@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Lucas",
    age: 25,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Medical science student, meal-prep devotee, and trivia night organiser.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 6, 4, 5, 2, 1, 6, 7, 5, 6, 6)
  },
  {
    id: "nina",
    email: "nina@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Nina",
    age: 21,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Maths student who likes salsa classes, long walks, and bad puns.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 5, 6, 5, 6, 4, 2, 5, 5, 4, 4, 5)
  },
  {
    id: "oscar",
    email: "oscar@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Oscar",
    age: 22,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Politics student, live music fan, and collector of vintage jackets.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 4, 5, 5, 6, 5, 4, 3, 2, 3, 2)
  },
  {
    id: "priya",
    email: "priya@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Priya",
    age: 24,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Public policy student, amateur baker, and weekend lake walker.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 4, 7, 5, 7, 3, 1, 4, 6, 5, 4, 6)
  },
  {
    id: "rafa",
    email: "rafa@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Rafa",
    age: 23,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Architecture student, cyclist, and always scouting the best coffee.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 5, 5, 4, 6, 5, 3, 7, 4, 6, 5, 4)
  },
  {
    id: "talia",
    email: "talia@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Talia",
    age: 20,
    gender: "woman",
    interestedIn: ["woman"],
    bio: "Biology student, plant parent, and quiet brunch enthusiast.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 3, 5, 4, 6, 2, 1, 3, 5, 5, 2, 5)
  },
  {
    id: "max",
    email: "max@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Max",
    age: 26,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Law student, swimmer, and strong believer in Sunday reset walks.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 3, 6, 3, 5, 3, 2, 6, 7, 6, 5, 5)
  },
  {
    id: "remy",
    email: "remy@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Remy",
    age: 22,
    gender: "non_binary",
    interestedIn: ["woman", "non_binary"],
    bio: "Creative writing student, cafe reader, and board game strategist.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 5, 4, 6, 5, 4, 4, 2, 3, 1, 2, 3)
  },
  {
    id: "grace",
    email: "grace@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Grace",
    age: 25,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "PhD candidate, sourdough experimenter, and sunset chaser.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 7, 4, 6, 3, 1, 5, 7, 4, 6, 6)
  },
  {
    id: "henry",
    email: "henry@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Henry",
    age: 21,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Statistics student, tennis player, and fan of low-key dinner dates.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 4, 5, 5, 5, 3, 2, 6, 6, 5, 4, 5)
  },
  {
    id: "lena",
    email: "lena@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Lena",
    age: 22,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Computer science student, pottery beginner, and dessert sharer.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 6, 4, 3, 4, 5, 3, 4, 4)
  },
  {
    id: "ben",
    email: "ben@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ben",
    age: 24,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Environmental studies student, climber, and farmers market regular.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 5, 5, 5, 5, 5, 4, 7, 3, 6, 3, 3)
  },
  {
    id: "sienna",
    email: "sienna@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Sienna",
    age: 23,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Commerce student, netball teammate, and brunch reservation expert.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 6, 4, 6, 5, 6, 5, 6, 3, 4, 4, 2)
  },
  {
    id: "eli",
    email: "eli@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Eli",
    age: 20,
    gender: "non_binary",
    interestedIn: ["man", "woman"],
    bio: "History student, op-shop hunter, and fan of spontaneous day trips.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 5, 5, 6, 4, 3, 4, 4, 2, 3, 4)
  },
  {
    id: "maya",
    email: "maya@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Maya",
    age: 24,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Anthropology student, ceramicist, and lover of slow Sundays.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 3, 6, 4, 7, 2, 1, 3, 5, 4, 2, 5)
  },
  {
    id: "tom",
    email: "tom@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Tom",
    age: 25,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Physics student, jazz listener, and excellent pancake maker.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 3, 6, 3, 5, 2, 1, 4, 7, 3, 6, 5)
  },
  {
    id: "ayla",
    email: "ayla@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ayla",
    age: 21,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Music student, choir regular, and always planning the next picnic.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 6, 5, 7, 6, 5, 3, 3, 4, 2, 2, 4)
  },
  {
    id: "jules",
    email: "jules@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Jules",
    age: 23,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Linguistics student, baker, and lover of long conversations.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 6, 5, 6, 3, 2, 3, 5, 3, 3, 5)
  },
  {
    id: "daniel",
    email: "daniel@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Daniel",
    age: 22,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Data science student, casual guitarist, and fan of night markets.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 5, 6, 5, 5, 4, 5, 4, 2, 3, 3)
  },
  {
    id: "aaron-seed-001",
    email: "aaron-seed-001@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Aaron",
    age: 18,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "ada-seed-002",
    email: "ada-seed-002@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ada",
    age: 25,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "alan-seed-003",
    email: "alan-seed-003@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Alan",
    age: 22,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "allegra-seed-004",
    email: "allegra-seed-004@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Allegra",
    age: 19,
    gender: "non_binary",
    interestedIn: ["woman", "man"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "anna-seed-005",
    email: "anna-seed-005@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Anna",
    age: 26,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "arthur-seed-006",
    email: "arthur-seed-006@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Arthur",
    age: 23,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "ash-seed-007",
    email: "ash-seed-007@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ash",
    age: 20,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "astrid-seed-008",
    email: "astrid-seed-008@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Astrid",
    age: 27,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "becca-seed-009",
    email: "becca-seed-009@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Becca",
    age: 24,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "brad-seed-010",
    email: "brad-seed-010@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Brad",
    age: 21,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "bridie-seed-011",
    email: "bridie-seed-011@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Bridie",
    age: 18,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "callum-seed-012",
    email: "callum-seed-012@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Callum",
    age: 25,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "carmen-seed-013",
    email: "carmen-seed-013@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Carmen",
    age: 22,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "dante-seed-014",
    email: "dante-seed-014@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Dante",
    age: 19,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "dara-seed-015",
    email: "dara-seed-015@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Dara",
    age: 26,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "evan-seed-016",
    email: "evan-seed-016@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Evan",
    age: 23,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "felix-seed-017",
    email: "felix-seed-017@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Felix",
    age: 20,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "fleur-seed-018",
    email: "fleur-seed-018@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Fleur",
    age: 27,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "gabe-seed-019",
    email: "gabe-seed-019@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Gabe",
    age: 24,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "gareth-seed-020",
    email: "gareth-seed-020@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Gareth",
    age: 21,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "gina-seed-021",
    email: "gina-seed-021@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Gina",
    age: 18,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "greta-seed-022",
    email: "greta-seed-022@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Greta",
    age: 25,
    gender: "non_binary",
    interestedIn: ["woman", "non_binary"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "harris-seed-023",
    email: "harris-seed-023@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Harris",
    age: 22,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "hazel-seed-024",
    email: "hazel-seed-024@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Hazel",
    age: 19,
    gender: "non_binary",
    interestedIn: ["woman", "man"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "hugo-seed-025",
    email: "hugo-seed-025@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Hugo",
    age: 26,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "ian-seed-026",
    email: "ian-seed-026@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ian",
    age: 23,
    gender: "non_binary",
    interestedIn: ["woman", "non_binary"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "inez-seed-027",
    email: "inez-seed-027@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Inez",
    age: 20,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "isla-seed-028",
    email: "isla-seed-028@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Isla",
    age: 27,
    gender: "man",
    interestedIn: ["woman", "man"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "jamal-seed-029",
    email: "jamal-seed-029@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Jamal",
    age: 24,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "jana-seed-030",
    email: "jana-seed-030@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Jana",
    age: 21,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "jaxon-seed-031",
    email: "jaxon-seed-031@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Jaxon",
    age: 18,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "jodie-seed-032",
    email: "jodie-seed-032@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Jodie",
    age: 25,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "jon-seed-033",
    email: "jon-seed-033@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Jon",
    age: 22,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "kara-seed-034",
    email: "kara-seed-034@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Kara",
    age: 19,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "keisha-seed-035",
    email: "keisha-seed-035@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Keisha",
    age: 26,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "kofi-seed-036",
    email: "kofi-seed-036@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Kofi",
    age: 23,
    gender: "non_binary",
    interestedIn: ["woman", "man"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "lana-seed-037",
    email: "lana-seed-037@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Lana",
    age: 20,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "louis-seed-038",
    email: "louis-seed-038@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Louis",
    age: 27,
    gender: "non_binary",
    interestedIn: ["woman", "non_binary"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "luca-seed-039",
    email: "luca-seed-039@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Luca",
    age: 24,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "marcy-seed-040",
    email: "marcy-seed-040@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Marcy",
    age: 21,
    gender: "non_binary",
    interestedIn: ["woman", "man"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "megan-seed-041",
    email: "megan-seed-041@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Megan",
    age: 18,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "milan-seed-042",
    email: "milan-seed-042@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Milan",
    age: 25,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "nadia-seed-043",
    email: "nadia-seed-043@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Nadia",
    age: 22,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "nigel-seed-044",
    email: "nigel-seed-044@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Nigel",
    age: 19,
    gender: "man",
    interestedIn: ["woman", "man"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "nolan-seed-045",
    email: "nolan-seed-045@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Nolan",
    age: 26,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "nyla-seed-046",
    email: "nyla-seed-046@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Nyla",
    age: 23,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "omar-seed-047",
    email: "omar-seed-047@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Omar",
    age: 20,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "oona-seed-048",
    email: "oona-seed-048@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Oona",
    age: 27,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "orla-seed-049",
    email: "orla-seed-049@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Orla",
    age: 24,
    gender: "man",
    interestedIn: ["woman"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "pavan-seed-050",
    email: "pavan-seed-050@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Pavan",
    age: 21,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "priya-seed-051",
    email: "priya-seed-051@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Priya",
    age: 18,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "quinn-seed-052",
    email: "quinn-seed-052@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Quinn",
    age: 25,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "raj-seed-053",
    email: "raj-seed-053@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Raj",
    age: 22,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "ruben-seed-054",
    email: "ruben-seed-054@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ruben",
    age: 19,
    gender: "woman",
    interestedIn: ["woman", "non_binary"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "rhea-seed-055",
    email: "rhea-seed-055@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Rhea",
    age: 26,
    gender: "man",
    interestedIn: ["woman", "non_binary"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "rory-seed-056",
    email: "rory-seed-056@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Rory",
    age: 23,
    gender: "non_binary",
    interestedIn: ["woman", "man"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "rosa-seed-057",
    email: "rosa-seed-057@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Rosa",
    age: 20,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "ryan-seed-058",
    email: "ryan-seed-058@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Ryan",
    age: 27,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "sadie-seed-059",
    email: "sadie-seed-059@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Sadie",
    age: 24,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "sasha-seed-060",
    email: "sasha-seed-060@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Sasha",
    age: 21,
    gender: "man",
    interestedIn: ["woman", "man"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "tara-seed-061",
    email: "tara-seed-061@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Tara",
    age: 18,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "tevin-seed-062",
    email: "tevin-seed-062@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Tevin",
    age: 25,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "toby-seed-063",
    email: "toby-seed-063@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Toby",
    age: 22,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "uma-seed-064",
    email: "uma-seed-064@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Uma",
    age: 19,
    gender: "man",
    interestedIn: ["woman", "man"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "vera-seed-065",
    email: "vera-seed-065@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Vera",
    age: 26,
    gender: "woman",
    interestedIn: ["man"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
  {
    id: "wade-seed-066",
    email: "wade-seed-066@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Wade",
    age: 23,
    gender: "non_binary",
    interestedIn: ["woman", "non_binary"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2)
  },
  {
    id: "wren-seed-067",
    email: "wren-seed-067@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Wren",
    age: 20,
    gender: "woman",
    interestedIn: ["man", "non_binary"],
    bio: "Loves trivia nights, ramen, and long walks around campus. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
  },
  {
    id: "zane-seed-068",
    email: "zane-seed-068@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Zane",
    age: 27,
    gender: "man",
    interestedIn: ["woman", "man"],
    bio: "Trying every specialty coffee stall between lectures. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2)
  },
  {
    id: "zofi-seed-069",
    email: "zofi-seed-069@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Zofi",
    age: 24,
    gender: "non_binary",
    interestedIn: ["woman", "man", "non_binary"],
    bio: "Weekend cyclist and podcast completionist. ANU.",
    relationshipIntent: "long_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(1, 3, 5, 7, 2, 4, 6, 1, 3, 5, 7, 2)
  },
  {
    id: "casey-seed-070",
    email: "casey-seed-070@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Casey69",
    age: 21,
    gender: "man",
    interestedIn: ["man", "non_binary"],
    bio: "Always down for galleries, picnics, and quiet study dates. ANU.",
    relationshipIntent: "long_term_open_to_short",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(4, 7, 3, 6, 2, 5, 1, 4, 7, 3, 6, 2)
  },
  {
    id: "casey-seed-071",
    email: "casey-seed-071@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Casey70",
    age: 18,
    gender: "non_binary",
    interestedIn: ["man", "non_binary"],
    bio: "Into climbing gyms, spreadsheets, and good playlists. ANU.",
    relationshipIntent: "short_term_open_to_long",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(7, 4, 1, 5, 2, 6, 3, 7, 4, 1, 5, 2)
  },
  {
    id: "casey-seed-072",
    email: "casey-seed-072@anu.edu.au",
    verifiedUniversityEmail: true,
    displayName: "Casey71",
    age: 25,
    gender: "woman",
    interestedIn: ["man", "woman"],
    bio: "Photography nerd and farmers market brunch regular. ANU.",
    relationshipIntent: "short_term",
    active: true,
    blockedUserIds: [],
    declinedUserIds: [],
    answers: answers(3, 1, 6, 4, 2, 7, 5, 3, 1, 6, 4, 2)
  },
];

